language: python
sudo: false

#env:
#   global:
#      - image=pythonnode_slave

matrix:
  exclude:
    - python:python2.6
  include:
    - python: 3.6

#matrix:
  #include:
    #- python: 2.7
    #  env: TRAVIS_NODE_VERSION="4"
    #- python: 2.7
    #  env: TRAVIS_NODE_VERSION="6"
    #- python: 3.5
    # env: TRAVIS_NODE_VERSION="6"
    #- python: 3.6
    #  env: TRAVIS_NODE_VERSION="6"

install:
  - curl https://nodejs.org/dist/v4.2.4/node-v4.2.4-linux-x64.tar.gz | tar xzvf - --exclude CHANGELOG.md --exclude LICENSE --exclude README.md --strip-components 1 -C /usr/local/
  - pip install -U pip
  - pip install --no-use-wheel buildbot # need no-use-wheel to get the test framework
  - pip install -r example/requirements.txt
  - pip install -e .
  - pip install mock

script:
  - python setup.py develop
  - trial buildbot_travis.tests

after_failure: "cat _trial_temp/test.log"
